'use strict';

const uuid = require('uuid');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return await queryInterface.bulkInsert('offers', [
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Circuitos Elétricos',
        offer_code: 'ECOM028',
        offer_code_classroom: 'm33NS1n3',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Projetos e Teoria de Linguagens',
        offer_code: 'ECOM145',
        offer_code_classroom: '0reofk8g',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Programação Orientada a Objetos',
        offer_code: 'ECOM450',
        offer_code_classroom: '2u0kdklb',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Linguagens de Programação',
        offer_code: 'ECOM026',
        offer_code_classroom: 'axkffdpr',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Compiladores',
        offer_code: 'ECOM750',
        offer_code_classroom: 'qgf11a5v',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Metodologia de Pesquisa',
        offer_code: 'ECOM130',
        offer_code_classroom: 'gac75q5i',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Computação Gráfica',
        offer_code: 'ECOM010',
        offer_code_classroom: 'twv9keay',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Probabilidade e Estatística',
        offer_code: 'ECOM145',
        offer_code_classroom: '15iqo2pq',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Tecnologia da Informação',
        offer_code: 'ECOM745',
        offer_code_classroom: 'lxtctqf4',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Introdução à Estatística',
        offer_code: 'ECOM123',
        offer_code_classroom: '0kksn7ka',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Redes de Computadores',
        offer_code: 'ECOM050',
        offer_code_classroom: '5yebk5ve',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Sistemas Distribuídos',
        offer_code: 'ECOM231',
        offer_code_classroom: 'vgeqifxw',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Circuitos Digitais',
        offer_code: 'ECOM980',
        offer_code_classroom: '7hyy085w',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Tópicos Especiais em Engenharia de Sistemas Computacionais ',
        offer_code: 'ECOM910',
        offer_code_classroom: 'ofk5flhg',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Circuitos Digitais',
        offer_code: 'ECOM980',
        offer_code_classroom: 'lvg5i0wx',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        offer_id: uuid.v4(),
        owner_id: 'f9584d5c-b11e-4148-8e12-e124782f9b9c',
        offer_name: 'Eletrônica',
        offer_code: 'ECOM912',
        offer_code_classroom: '5wc8xvyl',
        offer_link_classroom: '',
        offer_link_meets: '',
        offer_link_wpp: '',
        offer_link_tel: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return await queryInterface.bulkDelete('offers', null, {})
  }
};
